### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by ngdream**
i've update readme

### CODE REVIEW

**Review by naomi-lgbt — CHANGES_REQUESTED** [review]
Could you explain why these updates are needed?

For organisations, the `.github` readme displays from the `profile` directory, not the root directory.

**Comment by ngdream** [comment]
it just the .github readme.
Because not everyone knows that .github is used for organization configuration
we could just  add in the this readme ("organization's configuration folder")
that will help developer

**Comment by naomi-lgbt** [comment]
If that's the case, we should not remove the standard README template we use.

**Comment by ngdream** [comment]
> If that's the case, we should not remove the standard README template we use.

Reason to you

**Pull request closed without merging**
